#!/bin/bash

#	Add key for repository.

puts "ADDING REPOSITORY KEYS."

apt-key adv --keyserver keyserver.ubuntu.com --recv-keys \
	A03A4626

rm -r \
	/usr/share/keyrings/mesa-ppa.gpg

apt-key export A03A4626 | gpg --dearmour -o /usr/share/keyrings/mesa-ppa.gpg

apt -qq update
