#!/bin/bash

puts () { printf "\n\n --- %s\n" "$*"; }
add_keys () { apt-key adv --keyserver keyserver.ubuntu.com --recv-keys $@; }

#	Add key for repository.

puts "ADDING REPOSITORY KEYS."

 add_keys A03A4626

rm -r \
    /usr/share/keyrings/mesa-ppa.gpg
    
apt-key export A03A4626 | gpg --dearmour -o /usr/share/keyrings/mesa-ppa.gpg

apt -qq update
